import QtQuick
import Quickshell
import "../scripts/fuzzy.js" as Fuzzy

QtObject {
    id: root

    property string prefix: ": "
    property string name: "Emoji"
    property string placeholderText: "Search emoji..."

    property var _emojis: [
        { char: "😀", name: "grinning face" },
        { char: "😃", name: "grinning face big eyes" },
        { char: "😄", name: "grinning face smiling eyes" },
        { char: "😁", name: "beaming face smiling eyes" },
        { char: "😆", name: "grinning squinting face" },
        { char: "😅", name: "grinning face sweat" },
        { char: "🤣", name: "rolling on floor laughing" },
        { char: "😂", name: "face tears of joy" },
        { char: "🙂", name: "slightly smiling face" },
        { char: "🙃", name: "upside down face" },
        { char: "😉", name: "winking face" },
        { char: "😊", name: "smiling face smiling eyes" },
        { char: "😇", name: "smiling face halo" },
        { char: "🥰", name: "smiling face hearts" },
        { char: "😍", name: "heart eyes" },
        { char: "🤩", name: "star struck" },
        { char: "😘", name: "face blowing kiss" },
        { char: "😗", name: "kissing face" },
        { char: "😚", name: "kissing face closed eyes" },
        { char: "😋", name: "face savoring food" },
        { char: "😛", name: "face tongue" },
        { char: "😜", name: "winking face tongue" },
        { char: "🤪", name: "zany face" },
        { char: "😝", name: "squinting face tongue" },
        { char: "🤑", name: "money mouth face" },
        { char: "🤗", name: "hugging face" },
        { char: "🤭", name: "face hand over mouth" },
        { char: "🫢", name: "face with open eyes and hand over mouth" },
        { char: "🫣", name: "face with peeking eye" },
        { char: "🤫", name: "shushing face" },
        { char: "🤔", name: "thinking face" },
        { char: "🫡", name: "saluting face" },
        { char: "🤐", name: "zipper mouth face" },
        { char: "🤨", name: "face raised eyebrow" },
        { char: "😐", name: "neutral face" },
        { char: "😑", name: "expressionless face" },
        { char: "😶", name: "face without mouth" },
        { char: "😏", name: "smirking face" },
        { char: "😒", name: "unamused face" },
        { char: "🙄", name: "face rolling eyes" },
        { char: "😬", name: "grimacing face" },
        { char: "😮", name: "face with open mouth" },
        { char: "😯", name: "hushed face" },
        { char: "😲", name: "astonished face" },
        { char: "😳", name: "flushed face" },
        { char: "🥺", name: "pleading face" },
        { char: "😢", name: "crying face" },
        { char: "😭", name: "loudly crying face" },
        { char: "😤", name: "face steam from nose" },
        { char: "😠", name: "angry face" },
        { char: "😡", name: "pouting face" },
        { char: "🤬", name: "face with symbols on mouth" },
        { char: "😈", name: "smiling face horns" },
        { char: "👿", name: "angry face horns" },
        { char: "💀", name: "skull" },
        { char: "☠️", name: "skull crossbones" },
        { char: "💩", name: "pile of poo" },
        { char: "🤡", name: "clown face" },
        { char: "👹", name: "ogre" },
        { char: "👺", name: "goblin" },
        { char: "👻", name: "ghost" },
        { char: "👽", name: "alien" },
        { char: "🤖", name: "robot" },
        { char: "😺", name: "grinning cat" },
        { char: "😸", name: "grinning cat smiling eyes" },
        { char: "😹", name: "cat tears of joy" },
        { char: "😻", name: "heart eyes cat" },
        { char: "🙌", name: "raising hands" },
        { char: "👏", name: "clapping hands" },
        { char: "👍", name: "thumbs up" },
        { char: "👎", name: "thumbs down" },
        { char: "👊", name: "oncoming fist" },
        { char: "✊", name: "raised fist" },
        { char: "🤛", name: "left facing fist" },
        { char: "🤜", name: "right facing fist" },
        { char: "👋", name: "waving hand" },
        { char: "🤚", name: "raised back of hand" },
        { char: "🖐️", name: "hand splayed" },
        { char: "✋", name: "raised hand" },
        { char: "🖖", name: "vulcan salute" },
        { char: "🫶", name: "heart hands" },
        { char: "👌", name: "ok hand" },
        { char: "🤌", name: "pinched fingers" },
        { char: "🤏", name: "pinching hand" },
        { char: "✌️", name: "victory hand" },
        { char: "🤞", name: "crossed fingers" },
        { char: "🫰", name: "hand with index finger and thumb crossed" },
        { char: "🤟", name: "love you gesture" },
        { char: "🤘", name: "sign of horns" },
        { char: "🤙", name: "call me hand" },
        { char: "👈", name: "backhand index pointing left" },
        { char: "👉", name: "backhand index pointing right" },
        { char: "👆", name: "backhand index pointing up" },
        { char: "🖕", name: "middle finger" },
        { char: "👇", name: "backhand index pointing down" },
        { char: "☝️", name: "index pointing up" },
        { char: "🫵", name: "index pointing at viewer" },
        { char: "👍", name: "thumbs up" },
        { char: "💪", name: "biceps flexed" },
        { char: "🦵", name: "leg" },
        { char: "🦶", name: "foot" },
        { char: "👂", name: "ear" },
        { char: "👃", name: "nose" },
        { char: "🧠", name: "brain" },
        { char: "🫀", name: "anatomical heart" },
        { char: "👀", name: "eyes" },
        { char: "👁️", name: "eye" },
        { char: "👅", name: "tongue" },
        { char: "👄", name: "mouth" },
        { char: "💋", name: "kiss mark" },
        { char: "💘", name: "heart with arrow" },
        { char: "❤️", name: "red heart" },
        { char: "🩷", name: "pink heart" },
        { char: "🧡", name: "orange heart" },
        { char: "💛", name: "yellow heart" },
        { char: "💚", name: "green heart" },
        { char: "💙", name: "blue heart" },
        { char: "🩵", name: "light blue heart" },
        { char: "💜", name: "purple heart" },
        { char: "🖤", name: "black heart" },
        { char: "🩶", name: "gray heart" },
        { char: "🤍", name: "white heart" },
        { char: "🤎", name: "brown heart" },
        { char: "💕", name: "two hearts" },
        { char: "💞", name: "revolving hearts" },
        { char: "💓", name: "beating heart" },
        { char: "💗", name: "growing heart" },
        { char: "💖", name: "sparkling heart" },
        { char: "💔", name: "broken heart" },
        { char: "❤️‍🔥", name: "heart on fire" },
        { char: "💑", name: "couple with heart" },
        { char: "💏", name: "kiss" },
        { char: "⭐", name: "star" },
        { char: "🌟", name: "glowing star" },
        { char: "✨", name: "sparkles" },
        { char: "💥", name: "collision" },
        { char: "🔥", name: "fire" },
        { char: "💫", name: "dizzy" },
        { char: "💦", name: "sweat droplets" },
        { char: "💨", name: "dashing away" },
        { char: "🕳️", name: "hole" },
        { char: "💬", name: "speech balloon" },
        { char: "👁️‍🗨️", name: "eye in speech bubble" },
        { char: "🗨️", name: "left speech bubble" },
        { char: "🗯️", name: "right anger bubble" },
        { char: "💭", name: "thought balloon" },
        { char: "🛑", name: "stop sign" },
        { char: "📛", name: "name badge" },
        { char: "🚫", name: "prohibited" },
        { char: "❌", name: "cross mark" },
        { char: "⭕", name: "hollow red circle" },
        { char: "💢", name: "anger symbol" },
        { char: "♨️", name: "hot springs" },
        { char: "💩", name: "pile of poo" },
        { char: "☠️", name: "skull and crossbones" },
        { char: "⚠️", name: "warning" },
        { char: "🚸", name: "children crossing" },
        { char: "🔞", name: "no one under 18" },
        { char: "💯", name: "hundred points" },
        { char: "♻️", name: "recycling symbol" },
        { char: "✅", name: "check mark button" },
        { char: "❓", name: "question mark" },
        { char: "❔", name: "white question mark" },
        { char: "❕", name: "white exclamation mark" },
        { char: "❗", name: "exclamation mark" },
        { char: "〰️", name: "wavy dash" },
        { char: "🔴", name: "red circle" },
        { char: "🟠", name: "orange circle" },
        { char: "🟡", name: "yellow circle" },
        { char: "🟢", name: "green circle" },
        { char: "🔵", name: "blue circle" },
        { char: "🟣", name: "purple circle" },
        { char: "⚫", name: "black circle" },
        { char: "⚪", name: "white circle" },
        { char: "🟤", name: "brown circle" },
        { char: "🔺", name: "red triangle pointed up" },
        { char: "🔻", name: "red triangle pointed down" },
        { char: "🔸", name: "small orange diamond" },
        { char: "🔹", name: "small blue diamond" },
        { char: "🔶", name: "large orange diamond" },
        { char: "🔷", name: "large blue diamond" },
        { char: "🔳", name: "white square button" },
        { char: "🔲", name: "black square button" },
        { char: "▪️", name: "black small square" },
        { char: "▫️", name: "white small square" },
        { char: "⬛", name: "black medium square" },
        { char: "⬜", name: "white medium square" },
        { char: "🏁", name: "chequered flag" },
        { char: "🚩", name: "triangular flag" },
        { char: "🎌", name: "crossed flags" },
        { char: "🏴", name: "black flag" },
        { char: "🏳️", name: "white flag" },
        { char: "🏴‍☠️", name: "pirate flag" },
        { char: "🗺️", name: "world map" },
        { char: "🌍", name: "globe europe africa" },
        { char: "🌎", name: "globe americas" },
        { char: "🌏", name: "globe asia australia" },
        { char: "🗾", name: "map of japan" },
        { char: "🧭", name: "compass" },
        { char: "🏔️", name: "snow capped mountain" },
        { char: "⛰️", name: "mountain" },
        { char: "🌋", name: "volcano" },
        { char: "🏕️", name: "camping" },
        { char: "🏖️", name: "beach umbrella" },
        { char: "🏜️", name: "desert" },
        { char: "🏝️", name: "desert island" },
        { char: "🏞️", name: "national park" },
        { char: "🌄", name: "sunrise over mountains" },
        { char: "🌅", name: "sunrise" },
        { char: "🌆", name: "cityscape at dusk" },
        { char: "🌇", name: "sunset" },
        { char: "🌉", name: "bridge at night" },
        { char: "🎠", name: "carousel horse" },
        { char: "🎡", name: "ferris wheel" },
        { char: "🎢", name: "roller coaster" },
        { char: "💈", name: "barber pole" },
        { char: "🎪", name: "circus tent" },
        { char: "🚃", name: "railway car" },
        { char: "🚄", name: "high speed train" },
        { char: "🚅", name: "bullet train" },
        { char: "🚗", name: "car" },
        { char: "🚕", name: "taxi" },
        { char: "🚙", name: "suv" },
        { char: "🚌", name: "bus" },
        { char: "🚎", name: "trolleybus" },
        { char: "🏎️", name: "race car" },
        { char: "🚓", name: "police car" },
        { char: "🚑", name: "ambulance" },
        { char: "🚒", name: "fire engine" },
        { char: "🚐", name: "minibus" },
        { char: "🚚", name: "delivery truck" },
        { char: "🚛", name: "articulated lorry" },
        { char: "🚜", name: "tractor" },
        { char: "🏍️", name: "motorcycle" },
        { char: "🛵", name: "scooter" },
        { char: "🚲", name: "bicycle" },
        { char: "🛴", name: "kick scooter" },
        { char: "🚏", name: "bus stop" },
        { char: "🛣️", name: "motorway" },
        { char: "🛤️", name: "railway track" },
        { char: "⛽", name: "fuel pump" },
        { char: "🚨", name: "police car light" },
        { char: "🚥", name: "horizontal traffic light" },
        { char: "🚦", name: "vertical traffic light" },
        { char: "🛑", name: "stop sign" },
        { char: "🚧", name: "construction" },
        { char: "⚓", name: "anchor" },
        { char: "🛳️", name: "passenger ship" },
        { char: "⛵", name: "sailboat" },
        { char: "🚤", name: "speedboat" },
        { char: "✈️", name: "airplane" },
        { char: "🛩️", name: "small airplane" },
        { char: "🛫", name: "airplane departure" },
        { char: "🛬", name: "airplane arrival" },
        { char: "🪂", name: "parachute" },
        { char: "💺", name: "seat" },
        { char: "🚁", name: "helicopter" },
        { char: "🚟", name: "suspension railway" },
        { char: "🚠", name: "mountain cableway" },
        { char: "🚡", name: "aerial tramway" },
        { char: "🛰️", name: "satellite" },
        { char: "🚀", name: "rocket" },
        { char: "🛸", name: "flying saucer" },
        { char: "⌚", name: "watch" },
        { char: "📱", name: "mobile phone" },
        { char: "💻", name: "laptop" },
        { char: "⌨️", name: "keyboard" },
        { char: "🖥️", name: "desktop computer" },
        { char: "🖨️", name: "printer" },
        { char: "🖱️", name: "computer mouse" },
        { char: "🖲️", name: "trackball" },
        { char: "💾", name: "floppy disk" },
        { char: "💿", name: "cd" },
        { char: "📀", name: "dvd" },
        { char: "🎥", name: "movie camera" },
        { char: "🎞️", name: "film frames" },
        { char: "📽️", name: "film projector" },
        { char: "🎬", name: "clapper board" },
        { char: "📺", name: "television" },
        { char: "📷", name: "camera" },
        { char: "📸", name: "camera flash" },
        { char: "📹", name: "video camera" },
        { char: "🎙️", name: "studio microphone" },
        { char: "🎚️", name: "level slider" },
        { char: "🎛️", name: "control knobs" },
        { char: "🔈", name: "speaker low volume" },
        { char: "🔉", name: "speaker medium volume" },
        { char: "🔊", name: "speaker high volume" },
        { char: "📢", name: "loudspeaker" },
        { char: "📣", name: "megaphone" },
        { char: "🔔", name: "bell" },
        { char: "🔕", name: "bell with slash" },
        { char: "🎵", name: "musical note" },
        { char: "🎶", name: "musical notes" },
        { char: "🎤", name: "microphone" },
        { char: "🎧", name: "headphone" },
        { char: "🎼", name: "musical score" },
        { char: "🎹", name: "musical keyboard" },
        { char: "🪇", name: "maracas" },
        { char: "🥁", name: "drum" },
        { char: "🪘", name: "long drum" },
        { char: "🎷", name: "saxophone" },
        { char: "🎸", name: "guitar" },
        { char: "🎺", name: "trumpet" },
        { char: "🎻", name: "violin" },
        { char: "🎯", name: "bullseye" },
        { char: "🎳", name: "bowling" },
        { char: "🎲", name: "game die" },
        { char: "♟️", name: "chess pawn" },
        { char: "🃏", name: "joker" },
        { char: "🀄", name: "mahjong red dragon" },
        { char: "🎴", name: "flower playing cards" },
        { char: "🎮", name: "video game" },
        { char: "🕹️", name: "joystick" },
        { char: "🎰", name: "slot machine" },
        { char: "🧩", name: "puzzle piece" },
        { char: "🎨", name: "artist palette" },
        { char: "🪢", name: "knot" },
        { char: "🧵", name: "thread" },
        { char: "🪡", name: "sewing needle" },
        { char: "📚", name: "books" },
        { char: "📖", name: "open book" },
        { char: "📕", name: "closed book" },
        { char: "📗", name: "green book" },
        { char: "📘", name: "blue book" },
        { char: "📙", name: "orange book" },
        { char: "📔", name: "notebook with decorative cover" },
        { char: "📓", name: "notebook" },
        { char: "📒", name: "ledger" },
        { char: "📃", name: "page with curl" },
        { char: "📜", name: "scroll" },
        { char: "📄", name: "page facing up" },
        { char: "📰", name: "newspaper" },
        { char: "🗞️", name: "rolled up newspaper" },
        { char: "📑", name: "bookmark tabs" },
        { char: "🔖", name: "bookmark" },
        { char: "🏷️", name: "label" },
        { char: "💰", name: "money bag" },
        { char: "🪙", name: "coin" },
        { char: "💴", name: "yen banknote" },
        { char: "💵", name: "dollar banknote" },
        { char: "💶", name: "euro banknote" },
        { char: "💷", name: "pound banknote" },
        { char: "💸", name: "money with wings" },
        { char: "💳", name: "credit card" },
        { char: "🧾", name: "receipt" },
        { char: "✉️", name: "envelope" },
        { char: "📧", name: "email" },
        { char: "📨", name: "incoming envelope" },
        { char: "📩", name: "envelope with arrow" },
        { char: "📤", name: "outbox tray" },
        { char: "📥", name: "inbox tray" },
        { char: "📦", name: "package" },
        { char: "📪", name: "closed mailbox lowered flag" },
        { char: "📬", name: "open mailbox raised flag" },
        { char: "📮", name: "postal horn" },
        { char: "🗳️", name: "ballot box" },
        { char: "✏️", name: "pencil" },
        { char: "✒️", name: "black nib" },
        { char: "🖋️", name: "fountain pen" },
        { char: "🖊️", name: "pen" },
        { char: "🖌️", name: "paintbrush" },
        { char: "🖍️", name: "crayon" },
        { char: "📝", name: "memo" },
        { char: "📁", name: "file folder" },
        { char: "📂", name: "open file folder" },
        { char: "🗂️", name: "card index dividers" },
        { char: "📅", name: "calendar" },
        { char: "📆", name: "tear off calendar" },
        { char: "📇", name: "card index" },
        { char: "📈", name: "chart increasing" },
        { char: "📉", name: "chart decreasing" },
        { char: "📊", name: "bar chart" },
        { char: "📋", name: "clipboard" },
        { char: "📌", name: "pushpin" },
        { char: "📍", name: "round pushpin" },
        { char: "📎", name: "paperclip" },
        { char: "🖇️", name: "linked paperclips" },
        { char: "📏", name: "straight ruler" },
        { char: "📐", name: "triangular ruler" },
        { char: "✂️", name: "scissors" },
        { char: "🗃️", name: "card file box" },
        { char: "🗄️", name: "file cabinet" },
        { char: "🗑️", name: "wastebasket" },
        { char: "🔒", name: "locked" },
        { char: "🔓", name: "unlocked" },
        { char: "🔏", name: "locked with pen" },
        { char: "🔐", name: "locked with key" },
        { char: "🔑", name: "key" },
        { char: "🗝️", name: "old key" },
        { char: "🔨", name: "hammer" },
        { char: "🪓", name: "axe" },
        { char: "⛏️", name: "pick" },
        { char: "⚒️", name: "hammer and pick" },
        { char: "🛠️", name: "hammer and wrench" },
        { char: "🗡️", name: "dagger" },
        { char: "⚔️", name: "crossed swords" },
        { char: "🔫", name: "water pistol" },
        { char: "🛡️", name: "shield" },
        { char: "🔧", name: "wrench" },
        { char: "🔩", name: "nut and bolt" },
        { char: "⚙️", name: "gear" },
        { char: "🔗", name: "link" },
        { char: "⛓️", name: "chains" },
        { char: "🪝", name: "hook" },
        { char: "🧰", name: "toolbox" },
        { char: "🧲", name: "magnet" },
        { char: "🪜", name: "ladder" },
        { char: "⚗️", name: "alembic" },
        { char: "🧪", name: "test tube" },
        { char: "🧫", name: "petri dish" },
        { char: "🧬", name: "dna" },
        { char: "🔬", name: "microscope" },
        { char: "🔭", name: "telescope" },
        { char: "📡", name: "satellite antenna" },
        { char: "💡", name: "light bulb" },
        { char: "🔦", name: "flashlight" },
        { char: "🕯️", name: "candle" },
        { char: "🪔", name: "diya lamp" },
        { char: "🔌", name: "electric plug" },
        { char: "🔋", name: "battery" },
        { char: "🔪", name: "kitchen knife" },
        { char: "🫖", name: "teapot" },
        { char: "🍵", name: "teacup without handle" },
        { char: "🍶", name: "sake" },
        { char: "🍾", name: "bottle with popping cork" },
        { char: "🍷", name: "wine glass" },
        { char: "🍸", name: "cocktail glass" },
        { char: "🍹", name: "tropical drink" },
        { char: "🍺", name: "beer mug" },
        { char: "🍻", name: "clinking beer mugs" },
        { char: "🥂", name: "clinking glasses" },
        { char: "🥃", name: "tumbler glass" },
        { char: "🫗", name: "pouring liquid" },
        { char: "🥤", name: "cup with straw" },
        { char: "🧊", name: "ice" },
        { char: "🍽️", name: "fork and knife with plate" },
        { char: "🍴", name: "fork and knife" },
        { char: "🥄", name: "spoon" },
        { char: "🔪", name: "kitchen knife" },
        { char: "🫙", name: "jar" },
        { char: "🌱", name: "seedling" },
        { char: "🪴", name: "potted plant" },
        { char: "🌲", name: "evergreen tree" },
        { char: "🌳", name: "deciduous tree" },
        { char: "🌴", name: "palm tree" },
        { char: "🌵", name: "cactus" },
        { char: "🌾", name: "sheaf of rice" },
        { char: "🌿", name: "herb" },
        { char: "☘️", name: "shamrock" },
        { char: "🍀", name: "four leaf clover" },
        { char: "🍁", name: "maple leaf" },
        { char: "🍂", name: "fallen leaf" },
        { char: "🍃", name: "leaf fluttering in wind" },
        { char: "🪹", name: "empty nest" },
        { char: "🪺", name: "nest with eggs" },
        { char: "🍄", name: "mushroom" },
        { char: "🐀", name: "rat" },
        { char: "🐁", name: "mouse" },
        { char: "🐂", name: "ox" },
        { char: "🐃", name: "water buffalo" },
        { char: "🐄", name: "cow" },
        { char: "🐅", name: "tiger" },
        { char: "🐆", name: "leopard" },
        { char: "🐇", name: "rabbit" },
        { char: "🐈", name: "cat" },
        { char: "🐈‍⬛", name: "black cat" },
        { char: "🐉", name: "dragon" },
        { char: "🐊", name: "crocodile" },
        { char: "🐋", name: "whale" },
        { char: "🐌", name: "snail" },
        { char: "🐍", name: "snake" },
        { char: "🐎", name: "horse" },
        { char: "🐏", name: "ram" },
        { char: "🐐", name: "goat" },
        { char: "🐑", name: "ewe" },
        { char: "🐒", name: "monkey" },
        { char: "🐓", name: "rooster" },
        { char: "🐔", name: "chicken" },
        { char: "🐕", name: "dog" },
        { char: "🐖", name: "pig" },
        { char: "🐗", name: "boar" },
        { char: "🐘", name: "elephant" },
        { char: "🐙", name: "octopus" },
        { char: "🐚", name: "spiral shell" },
        { char: "🐛", name: "bug" },
        { char: "🐜", name: "ant" },
        { char: "🐝", name: "honeybee" },
        { char: "🐞", name: "lady beetle" },
        { char: "🐟", name: "fish" },
        { char: "🐠", name: "tropical fish" },
        { char: "🐡", name: "blowfish" },
        { char: "🐢", name: "turtle" },
        { char: "🐣", name: "hatching chick" },
        { char: "🐤", name: "baby chick" },
        { char: "🐥", name: "front facing baby chick" },
        { char: "🐦", name: "bird" },
        { char: "🐧", name: "penguin" },
        { char: "🐨", name: "koala" },
        { char: "🐩", name: "poodle" },
        { char: "🐪", name: "camel" },
        { char: "🐫", name: "two hump camel" },
        { char: "🐬", name: "dolphin" },
        { char: "🐭", name: "mouse face" },
        { char: "🐮", name: "cow face" },
        { char: "🐯", name: "tiger face" },
        { char: "🐰", name: "rabbit face" },
        { char: "🐱", name: "cat face" },
        { char: "🐲", name: "dragon face" },
        { char: "🐳", name: "spouting whale" },
        { char: "🐴", name: "horse face" },
        { char: "🐵", name: "monkey face" },
        { char: "🐶", name: "dog face" },
        { char: "🐷", name: "pig face" },
        { char: "🐸", name: "frog" },
        { char: "🐹", name: "hamster" },
        { char: "🐺", name: "wolf" },
        { char: "🐻", name: "bear" },
        { char: "🐻‍❄️", name: "polar bear" },
        { char: "🐼", name: "panda" },
        { char: "🦄", name: "unicorn" },
        { char: "🦅", name: "eagle" },
        { char: "🦆", name: "duck" },
        { char: "🦇", name: "bat" },
        { char: "🦈", name: "shark" },
        { char: "🦉", name: "owl" },
        { char: "🦊", name: "fox" },
        { char: "🦋", name: "butterfly" },
        { char: "🦌", name: "deer" },
        { char: "🦍", name: "gorilla" },
        { char: "🦎", name: "lizard" },
        { char: "🦏", name: "rhinoceros" },
        { char: "🦐", name: "shrimp" },
        { char: "🦑", name: "squid" },
        { char: "🦒", name: "giraffe" },
        { char: "🦓", name: "zebra" },
        { char: "🦔", name: "hedgehog" },
        { char: "🦕", name: "sauropod" },
        { char: "🦖", name: "trex" },
        { char: "🦗", name: "cricket" },
        { char: "🥀", name: "wilted flower" },
        { char: "🌹", name: "rose" },
        { char: "🌺", name: "hibiscus" },
        { char: "🌻", name: "sunflower" },
        { char: "🌼", name: "blossom" },
        { char: "🌽", name: "ear of corn" },
        { char: "🌶️", name: "hot pepper" },
        { char: "🥑", name: "avocado" },
        { char: "🥒", name: "cucumber" },
        { char: "🥓", name: "bacon" },
        { char: "🥔", name: "potato" },
        { char: "🥕", name: "carrot" },
        { char: "🥖", name: "baguette bread" },
        { char: "🥗", name: "green salad" },
        { char: "🥘", name: "shallow pan of food" },
        { char: "🥙", name: "stuffed flatbread" },
        { char: "🥚", name: "egg" },
        { char: "🥛", name: "glass of milk" },
        { char: "🥜", name: "peanuts" },
        { char: "🥝", name: "kiwi fruit" },
        { char: "🥞", name: "pancakes" },
        { char: "🥟", name: "dumpling" },
        { char: "🥠", name: "fortune cookie" },
        { char: "🥡", name: "takeout box" },
        { char: "🦀", name: "crab" },
        { char: "🦐", name: "shrimp" },
        { char: "🦞", name: "lobster" },
        { char: "🦪", name: "oyster" },
        { char: "🍏", name: "green apple" },
        { char: "🍎", name: "red apple" },
        { char: "🍐", name: "pear" },
        { char: "🍑", name: "peach" },
        { char: "🍒", name: "cherries" },
        { char: "🍓", name: "strawberry" },
        { char: "🫐", name: "blueberries" },
        { char: "🍅", name: "tomato" },
        { char: "🍆", name: "eggplant" },
        { char: "🍇", name: "grapes" },
        { char: "🍈", name: "melon" },
        { char: "🍉", name: "watermelon" },
        { char: "🍊", name: "tangerine" },
        { char: "🍋", name: "lemon" },
        { char: "🍌", name: "banana" },
        { char: "🍍", name: "pineapple" },
        { char: "🍠", name: "roasted sweet potato" },
        { char: "🍡", name: "dango" },
        { char: "🍢", name: "oden" },
        { char: "🍣", name: "sushi" },
        { char: "🍤", name: "fried shrimp" },
        { char: "🍥", name: "fish cake" },
        { char: "🍩", name: "doughnut" },
        { char: "🍪", name: "cookie" },
        { char: "🍫", name: "chocolate bar" },
        { char: "🍬", name: "candy" },
        { char: "🍭", name: "lollipop" },
        { char: "🍮", name: "custard" },
        { char: "🍯", name: "honey pot" },
        { char: "🍰", name: "shortcake" },
        { char: "🍱", name: "bento box" },
        { char: "🍲", name: "pot of food" },
        { char: "🍳", name: "cooking" },
        { char: "🍴", name: "fork and knife" },
        { char: "🍵", name: "teacup without handle" },
        { char: "🍶", name: "sake" },
        { char: "🍷", name: "wine glass" },
        { char: "🍸", name: "cocktail glass" },
        { char: "🍹", name: "tropical drink" },
        { char: "🍺", name: "beer mug" },
        { char: "🍻", name: "clinking beer mugs" },
        { char: "🥂", name: "clinking glasses" },
        { char: "🥃", name: "tumbler glass" },
        { char: "🫗", name: "pouring liquid" },
        { char: "🥤", name: "cup with straw" },
        { char: "🧊", name: "ice cube" },
        { char: "☀️", name: "sun" },
        { char: "☁️", name: "cloud" },
        { char: "⛅", name: "sun behind cloud" },
        { char: "🌤️", name: "sun behind small cloud" },
        { char: "🌥️", name: "sun behind large cloud" },
        { char: "🌦️", name: "sun behind rain cloud" },
        { char: "🌈", name: "rainbow" },
        { char: "🌧️", name: "cloud with rain" },
        { char: "🌨️", name: "cloud with snow" },
        { char: "🌩️", name: "cloud with lightning" },
        { char: "⚡", name: "high voltage" },
        { char: "🌪️", name: "tornado" },
        { char: "🌫️", name: "fog" },
        { char: "🌬️", name: "wind face" },
        { char: "🌀", name: "cyclone" },
        { char: "🌈", name: "rainbow" },
        { char: "🌂", name: "closed umbrella" },
        { char: "☂️", name: "umbrella" },
        { char: "☔", name: "umbrella with rain drops" },
        { char: "⛱️", name: "umbrella on ground" },
        { char: "❄️", name: "snowflake" },
        { char: "☃️", name: "snowman" },
        { char: "🔥", name: "fire" },
        { char: "💧", name: "droplet" },
        { char: "🌊", name: "water wave" },
        { char: "🕐", name: "one oclock" },
        { char: "🕑", name: "two oclock" },
        { char: "🕒", name: "three oclock" },
        { char: "🕓", name: "four oclock" },
        { char: "🕔", name: "five oclock" },
        { char: "🕕", name: "six oclock" },
        { char: "🕖", name: "seven oclock" },
        { char: "🕗", name: "eight oclock" },
        { char: "🕘", name: "nine oclock" },
        { char: "🕙", name: "ten oclock" },
        { char: "🕚", name: "eleven oclock" },
        { char: "🕛", name: "twelve oclock" },
        { char: "🔄", name: "counterclockwise arrows button" },
        { char: "🔃", name: "clockwise vertical arrows" },
        { char: "⏪", name: "fast reverse button" },
        { char: "⏩", name: "fast forward button" },
        { char: "⏮️", name: "last track button" },
        { char: "⏭️", name: "next track button" },
        { char: "⏸️", name: "pause button" },
        { char: "⏹️", name: "stop button" },
        { char: "⏺️", name: "record button" },
        { char: "▶️", name: "play button" },
        { char: "◀️", name: "reverse button" },
        { char: "🔼", name: "upwards button" },
        { char: "🔽", name: "downwards button" },
        { char: "⏫", name: "fast up button" },
        { char: "⏬", name: "fast down button" },
        { char: "🔀", name: "shuffle tracks button" },
        { char: "🔁", name: "repeat button" },
        { char: "🔂", name: "repeat single button" },
        { char: "🔅", name: "dim button" },
        { char: "🔆", name: "bright button" },
        { char: "📶", name: "antenna bars" },
        { char: "📳", name: "vibration mode" },
        { char: "📴", name: "mobile phone off" },
        { char: "➕", name: "plus" },
        { char: "➖", name: "minus" },
        { char: "✖️", name: "multiply" },
        { char: "➗", name: "divide" },
        { char: "🟰", name: "heavy equals sign" },
        { char: "♾️", name: "infinity" },
        { char: "⁉️", name: "exclamation question mark" },
        { char: "™️", name: "trade mark" },
        { char: "©️", name: "copyright" },
        { char: "®️", name: "registered" },
        { char: "🔒", name: "locked" },
        { char: "🔓", name: "unlocked" },
        { char: "🔏", name: "locked with pen" },
        { char: "🔐", name: "locked with key" },
        { char: "🔑", name: "key" },
        { char: "🔎", name: "magnifying glass tilted left" },
        { char: "🔍", name: "magnifying glass tilted right" },
        { char: "🪪", name: "identification card" },
        { char: "💉", name: "syringe" },
        { char: "🩸", name: "drop of blood" },
        { char: "💊", name: "pill" },
        { char: "🩹", name: "adhesive bandage" },
        { char: "🩺", name: "stethoscope" },
        { char: "🚿", name: "shower" },
        { char: "🛁", name: "bathtub" },
        { char: "🪥", name: "toothbrush" },
        { char: "🧴", name: "lotion bottle" },
        { char: "🧷", name: "safety pin" },
        { char: "🧹", name: "broom" },
        { char: "🧺", name: "basket" },
        { char: "🧻", name: "roll of paper" },
        { char: "🪣", name: "bucket" },
        { char: "🧼", name: "soap" },
        { char: "🫧", name: "bubbles" },
        { char: "🧽", name: "sponge" },
        { char: "🧯", name: "fire extinguisher" },
        { char: "🛒", name: "shopping cart" },
        { char: "🚬", name: "cigarette" },
        { char: "⚰️", name: "coffin" },
        { char: "🪦", name: "headstone" },
        { char: "⚱️", name: "funeral urn" },
        { char: "🗿", name: "moai" },
        { char: "🪧", name: "placard" },
        { char: "🪪", name: "identification card" },
    ]

    function query(text) {
        if (!text || !text.trim())
            return root._emojis.slice(0, 50).map(function(e) { return e })

        var results = Fuzzy.go(text, root._emojis, {
            key: "name",
            limit: 50,
            threshold: -10000
        })
        if (results.length > 0)
            return results.map(function(r) { return r.obj })

        var lower = text.toLowerCase()
        var fallback = []
        for (var i = 0; i < root._emojis.length; i++) {
            if (root._emojis[i].name.toLowerCase().indexOf(lower) !== -1)
                fallback.push(root._emojis[i])
        }
        return fallback.slice(0, 50)
    }

    function textFor(entry) { return entry ? entry.char : "" }

    function activate(entry) {
        if (entry && entry.char)
            Quickshell.execDetached(["bash", "-c",
                "echo -n \"$1\" | wl-copy",
                "copy", entry.char])
    }

    property Component itemComponent: Component {
        MouseArea {
            id: rootItem
            required property var modelData
            required property bool selected
            required property var colors
            required property real uiScale
            property var launcher: null
            property int itemIndex: -1

            height: Math.round(44 * uiScale)
            hoverEnabled: true
            onClicked: {
                if (launcher && itemIndex >= 0) {
                    launcher.currentIndex = itemIndex
                    launcher.selectCurrent()
                }
            }
            onEntered: {
                if (launcher && itemIndex >= 0) {
                    launcher.currentIndex = itemIndex
                }
            }

            Rectangle {
                anchors.fill: parent
                color: selected ? colors.highlighted : "transparent"
                radius: Math.round(6 * uiScale)
            }

            Row {
                anchors.left: parent.left
                anchors.leftMargin: Math.round(10 * uiScale)
                anchors.verticalCenter: parent.verticalCenter
                spacing: Math.round(8 * uiScale)

                Text {
                    text: modelData ? modelData.char : ""
                    font.pointSize: 14
                    anchors.verticalCenter: parent.verticalCenter
                }

                Text {
                    text: modelData ? (": " + modelData.name) : ""
                    color: colors.text
                    font.pointSize: 9
                    font.family: "monospace"
                    anchors.verticalCenter: parent.verticalCenter
                }
            }
        }
    }
}
