#!/bin/sh
command -v powerprofilesctl >/dev/null 2>&1 || exit 0
command -v indicator >/dev/null 2>&1 || exit 0
PROFILE="${1:-balanced}"
powerprofilesctl set "$PROFILE"
indicator "Power Profile Indicator" "Power Profile" "$PROFILE"
